# Generated by Django 3.2.12 on 2022-03-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220307_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Office_name',
            new_name='office_name',
        ),
    ]
